# Generated by Django 6.0.1 on 2026-01-07 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur/Réalisateur/Artiste')),
                ('annee', models.IntegerField(verbose_name='Année de publication')),
                ('type_media', models.CharField(choices=[('LIVRE', 'Livre'), ('DVD', 'DVD'), ('CD', 'CD'), ('JEU', 'Jeu de plateau')], max_length=10, verbose_name='Type')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='JeuPlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du jeu')),
                ('createur', models.CharField(max_length=100, verbose_name='Créateur')),
                ('joueurs_min', models.IntegerField(default=1, verbose_name='Joueurs minimum')),
                ('joueurs_max', models.IntegerField(default=4, verbose_name='Joueurs maximum')),
            ],
            options={
                'verbose_name': 'Jeu de plateau',
                'verbose_name_plural': 'Jeux de plateau',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('bloque', models.BooleanField(default=False, verbose_name='Membre bloqué')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('artiste', models.CharField(max_length=100, verbose_name='Artiste')),
                ('pistes', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pistes')),
            ],
            bases=('bibliotheque.media',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('realisateur', models.CharField(max_length=100, verbose_name='Réalisateur')),
                ('duree', models.IntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
            ],
            bases=('bibliotheque.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotheque.media')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
            ],
            bases=('bibliotheque.media',),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('date_retour_prevue', models.DateField(verbose_name='Date de retour prévue')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.media', verbose_name='Média')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
            },
        ),
    ]
